### ISSUE TITLE
Revolt API 0.5.3 support.

### ISSUE THREAD

**Issue by insertish** [Darkflame72/defectio#15]
Since your library uses user authentication, you need to update certain routes. (https://github.com/revoltchat/delta/issues/63)

Revolt's user authentication flow has been overhauled, changes include:
- Completely re-done REST API.
- Deprecation of `x-user-id` header.

Documentation is available here: https://developers.revolt.chat/api/#tag/Account

**Comment by Darkflame72** [comment]
Currently authentication in the websocket and http are done.

Need to do the rest api endpoint changes

**Comment by Darkflame72** [comment]
@all-contributors please add @insertish for bugs

**Comment by Darkflame72** [comment]
After testing all endpoints now work with the change
